name: Changelog

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: '--deny warnings'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  changelog:
    name: Create changelog
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-tags: 'true'
          fetch-depth: 0
      - name: Generate a changelog
        run: |
          date +%Y-%m-%d >> CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changelog
        run: |
          git checkout -b "changelog/${VERSION}"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore: Update changelog"
          git push origin "changelog/${VERSION}" --force
        env:
          VERSION: 1.3.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: "changelog/${{ env.VERSION }}"
          persist-credentials: false
        env:
          VERSION: 1.3.0
      - name: Create pull request for changelog
        run: |
          alreadyExists=$(gh pr list --json headRefName | jq '.[] | select(.headRefName == "changelog/${VERSION}") | any')
          if [[ "$alreadyExists" == "" ]]; then
            branch=$(git branch --show-current)
            gh pr create --head "$branch" --title "Changelog for ${VERSION}" --body "This PR updates the changelog for version ${VERSION}."
          fi
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 1.3.0
