name: prepare

on:
  workflow_dispatch:
    inputs:
      #type:
      #  type: choice
      #  required: true
      #  options:
      #    - release
      #    - feature
      version:
        type: string
        required: true
        description: la version à préparer, par exemple "1.68.3"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Create branch
        run: |
          BRANCH_NAME="release/${VERSION}"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
        env:
          VERSION=${{ github.event.inputs.version }}
      - name: Update Chart.yaml
        run: |
          sed -i "s/^version: .*/version: ${VERSION}/" chart/
          sed -i "s/^appVersion: .*/appVersion: ${VERSION}/" chart/Chart.yaml
      - name: Commit changes
        run: |
          git add chart/Chart.yaml
          git commit -m "Prepare release ${VERSION}"
          git push origin $BRANCH_NAME
        env:
          VERSION=${{ github.event.inputs.version }}
      - name: Create Pull Request
        run: gh pr create --head "$BRANCH_NAME" --title "release ${VERSION}" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
