name: project
on:
  pull_request:
    types: [opened, closed, reopened]
jobs:

  normalize-pull-request-title:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Compute  Pull Request Title
        uses: actions/github-script@v7
        id: compute_title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          result-encoding: string
          script: |
            let pullRequestTitle = process.env.TITLE || process.argv[2];
            const regex = /([0-9]{4,}(-[0-9]{4,})*)[\s:\-\]]*(.+)/;
            const match = pullRequestTitle.match(regex);
            if (match) {
              pullRequestTitle = `TEST-${match[1]} - ${match[3].trim()}`;
            }
              console.log(pullRequestTitle);
              return pullRequestTitle;
      - name: Change Pull Request Title
        if: steps.compute_title.outputs.result != github.event.pull_request.title
        run: |
          echo "::notice title=Pull Request Title:: Changement du titre de la Pull Request en '${{ steps.compute_title.outputs.result }}'"
          gh pr edit ${{ github.event.pull_request.number }} --title "${{ steps.compute_title.outputs.result }}"