name: project
on:
  pull_request:
    types: [opened, closed, reopened]
jobs:

  normalize-pull-request-title:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Compute  Pull Request Title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
            const regex = /([0-9]{4,}(-[0-9]{4,})*)[\s:\-\]]*(.+)/;
            let title = pr.title;
            const match = title.match(regex);
            if (match) {
                title = `RPUSATIS-${match[1]} - ${match[3].trim()}`;
            }

            let body = pr.body || "";
            if (!body.trim().endsWith("thanks")) {
                body = body.trim() + "\n\nthanks";
            }
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              title: title,
              body: body
            });