name: project
on:
  pull_request:
    types: [opened, closed, reopened]
jobs:

  normalize-pull-request-title:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Compute  Pull Request Title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
            const regex = /([0-9]{4,}(-[0-9]{4,})*)[\s:\-\]]*(.+)/;

            let title = pr.title;
            let body = pr.body || "";
            const match = title.match(regex);
            if (match) {
                const ticket = `RPUSATIS-${match[1]}`;
                title = `${ticket} - ${match[3].trim()}`;
                badge = `[![${ticket}](https://img.shields.io/badge/${ticket.replace('-', '--')}-black?labelColor=black&logo=jira)](https://atlassian.net/browse/${ticket})`
                if(!body.includes(badge)) {
                    body = `${badge}\n\n${body}`;
                }
            }
            await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: title,
                body: body
            });