name: project
on:
  pull_request:
    types: [opened, closed, reopened ]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{ github.event.action }}
      - name: Add PR to GitHub Project
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: 'https://github.com/users/Mcdostone/projects/3'
          github-token: ${{ secrets.PROJECT_MANAGEMENT}}
          labeled: 'In Progress'

      - uses: actions/add-to-project@v1.0.2
        if: github.event.action == 'merged'
        with:
          project-url: 'https://github.com/users/Mcdostone/projects/3'
          github-token: ${{ secrets.PROJECT_MANAGEMENT}}
          labeled: 'Merged'


  on-pull-request-merged:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
    steps:
#      - name: Update the status of the PR when merged
#        uses: srggrs/assign-one-project-github-action@1.2.1
#        with:
#          project: 'https://github.com/orgs/MAIFX/projects/13/'
#          column_name: 'Merged'
      
      - uses: actions/checkout@v4.2.2
      - name: Add milestone to the merged PR
        run: |
          VERSION=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/release\///')
          echo "::notice title=Milestone:: Ajout de la milestone ${VERSION}"
          gh pr edit ${{ github.event.pull_request.number }} --milestone "${VERSION}"
        env:
          GH_TOKEN: ${{ github.token }}