name: project
on:
  pull_request:
    types: [opened, closed ]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to GitHub Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/users/Mcdostone/projects/3'
          column_name: 'In Progress'
        env:
          MY_GITHUB_TOKEN: ${{ github.token }}

      - name: Update the status of the PR when merged
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'merged'
        with:
          project: 'https://github.com/users/Mcdostone/projects/3'
          column_name: 'Merged'


  on-pull-request-merged:
    runs-on: ubuntu-latest
#    if: github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
    steps:
#      - name: Update the status of the PR when merged
#        uses: srggrs/assign-one-project-github-action@1.2.1
#        with:
#          project: 'https://github.com/orgs/MAIFX/projects/13/'
#          column_name: 'Merged'
      
      - name: Add milestone to the merged PR
        run: 
          VERSION=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/release\///')
          gh pr edit ${{ github.event.pull_request.number }} --milestone "${VERSION}"
        env:
          GH_TOKEN: ${{ github.token }}